### ISSUE TITLE
Dynamic Sitemap Generator

### ISSUE THREAD

**Issue by RenaudGagne** [steemdocs/steemdocs#29]
## Feature request

Dynamic Sitemap Generator

#### What problem does this feature solve?

Increase SERP crawling capacities for better search engine rankings.

#### What does the proposed API look like?
N/A
#### How should this be implemented in your opinion?

We should have a sitemap.xml that I can submit to both Google and Bing.

#### Are you willing to work on this yourself?**

I'm willing to do the installation once the feature is implemented.

**Comment by adasq** [comment]
https://steemit.com/steemdocs/@cryptoctopus/steemdocs-net-bounty-dynamic-sitemap-xml-50-steem-upvote-from-utopian-and-me#@adasq/re-cryptoctopus-steemdocs-net-bounty-dynamic-sitemap-xml-50-steem-upvote-from-utopian-and-me-20181027t095534001z

**Comment by RenaudGagne** [comment]
You rock @adasq ! I've made my upvote, sent you 50 Steem and hopefully utopian will reward you appropriately. I hope you'll want to keep contributing to Steemdocs...we really want to have great documentation for Steem and your help would be most welcomed.

**Comment by adasq** [comment]
Thank you @RenaudGagne for the reward!
I see value in the project, so it was even more fun to contribute. 
Thanks for the effort you put into STEEM blockchain as well. Community needs more people like you :)

**Comment by adasq** [comment]
According to a note raised by Utopian moderator:

Some of `.md` files located directly in `docs` dir are also included in https://steemdocs.net/sitemap.xml:

- https://steemdocs.net/GLOSSARY_CONTRIBUTING.html
- https://steemdocs.net/No-Entry-Template.html

I don't fill it is a critical issue, but if you feel it should be fixed, I can move it out of `docs` directory to the project root - that is the easiest way, but we might also ignore it somehow, while building `sitemap.xml`.

**Comment by adasq** [comment]
@kareniel Sure, will fix it.

**Comment by kareniel** [comment]
Thanks a lot for your work @adasq ! This is super appreciated! :) 

Anything else to mention before we close this?

**Comment by adasq** [comment]
I think it is enough to close it :)
