### ISSUE TITLE
The link to code_of_conduct.md page shows no content

### ISSUE THREAD

**Issue by littleboy0k** [steemdocs/steemdocs#38]
The link https://github.com/kareniel/steem-docs/code_of_conduct.md in the contrbuting.md page is either broken or doesn't have any content.

**Comment by RenaudGagne** [comment]
Hi! Where on the website is that link located? Which page?

**Comment by littleboy0k** [comment]
> Hi! Where on the website is that link located? Which page?

https://github.com/steemdocs/steemdocs/blob/master/CONTRIBUTING.md the page was updated after I posted this issue. I am closing the issue since the issue has been resolved.

**Comment by RenaudGagne** [comment]
THank you @littleboy0k !
